version: 2.1

jobs:
  build_backend:
    docker:
      - image: cimg/python:3.11 # ✅ Correct Python image
    working_directory: ~/project
    steps:
      - checkout

      - run:
          name: Create and activate virtual environment
          command: |
            cd backend
            python -m venv venv
            source venv/bin/activate
            pip install --upgrade pip
            pip install -r requirements.txt

      - run:
          name: Check installed packages
          command: |
            cd backend
            source venv/bin/activate
            pip list

      - run:
          name: Run Python tests
          command: |
            cd backend
            source venv/bin/activate  
            pytest -v

  build_frontend:
    docker:
      - image: circleci/node:16 # ✅ Correct Node.js image
    working_directory: ~/project/frontend # ✅ Change to frontend directory
    steps:
      - checkout
      - run:
          name: Debug - List files in frontend directory
          command: ls -la ~/project/frontend
      - run:
          name: Install Node.js dependencies
          command: |
            cd frontend
            npm install --legacy-peer-deps  # Add this flag if there are dependency conflicts
      - run:
          name: Debug - List node_modules
          command: |
            ls -la ~/project/frontend/node_modules
      - run:
          name: Build React app
          command: |
            cd frontend
            npm run build
      - persist_to_workspace:
          root: ~/project/frontend
          paths:
            - build # ✅ Store the build for deployment

  deploy:
    docker:
      - image: cimg/python:3.11
    working_directory: ~/project/backend
    steps:
      - attach_workspace:
          at: ~/workspace # ✅ Correct workspace path

      - run:
          name: Create Virtual Environment
          command: |
            python3 -m venv venv
            source venv/bin/activate
            pip install --upgrade pip

      - run:
          name: Print Working Directory
          command: ls -la

      - run:
          name: List Workspace Contents
          command: ls -la ~/workspace

      - run:
          name: Deploy Backend and Frontend
          command: |
            # Activate venv before deployment (if needed)
            source venv/bin/activate
            # Deploy backend (replace with actual deploy steps)
            echo "Deploying backend..."
            # Deploy frontend build files
            scp -r ~/workspace/build/* hma14@ai.lottotry.com:/var/www/html/

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build_backend
      - build_frontend:
          requires:
            - build_backend
      - deploy:
          requires:
            - build_frontend
